language: rust

branches:
  only:
    - master

cache:
  - cargo: true

env:
  - CARGO_TERM_VERBOSE=true

script: >-
  cargo update &&
  cargo test

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.26.2
    - rust: stable
      os: osx
    - rust: stable
      os: windows
      