version: 0.0.{build}

branches:
  only:
    - master

environment:
  global:
    PROJECT: rhq
    TOOLCHAIN: stable
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu

install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/i686-pc-windows-msvc/rustup-init.exe'
  - rustup-init.exe --no-modify-path --default-toolchain=%TOOLCHAIN% --default-host=%TARGET% -y --verbose
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --target=%TARGET%

test_script:
  - cargo test --target=%TARGET%

after_test:
  - .\ci\make_artifact.bat

artifacts:
  - path: $(PKGNAME)

deploy:
  appveyor_repo_tag: true
  provider: GitHub
  draft: false
  prerelease: false
  force_update: true
  auth_token:
    secure: o2CG38son6ujYzjHBQ+S7mquCIh8iNGTE4PXn8XNfMtxPz7b9tPoXuW0dEz8QsX7
  on:
    branch: master
    appveyor_repo_tag: true
