[package]
name = "rhq-cli"
version = "0.2.8"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[[bin]]
name = "rhq"
path = "main.rs"

[dependencies]
clap = "^2.20.3"
env_logger = "^0.4.0"
shlex = "0.1"
rhq = { version = "0.2.8", path = "../rhq" }
