# The path of root directory to manage cloned repositories.
root = "{{ root_dir }}"

# The default hostname when omitted
default_host = "github.com"

# Patterns to search local repositories.
includes = [
    "~/.dotfiles",
]

# Patterns to ignore repositories.
excludes = [
    "~/.cache/**/*",
]
